name: oms_salesforce
description: A new Flutter project.

publish_to: 'none'

# UPTO ANDROID 
version: 1.0.6+9

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  page_transition: ^2.0.9
  fluttertoast: ^8.1.2
  nepali_utils: ^3.0.3
  connectivity_plus: ^6.0.1
  dio: ^5.2.1+1
  sqflite: ^2.2.4+1
  path: ^1.8.2
  path_provider: ^2.0.12
  device_info_plus: ^10.0.1
  flutter_speed_dial: ^7.0.0
  nepali_date_picker: ^6.0.0
  permission_handler: ^10.2.1
  # google_maps_flutter: ^2.2.5
  geolocator: ^11.0.0
  flutter_slidable: ^3.0.0
  image_picker: ^1.0.1
  maps_launcher: ^2.2.0
  material: ^1.0.0+2
  # flutter_inappwebview: ^5.7.2+3
  flutter_map: ^6.1.0
  dropdown_button2: ^2.3.8
  intl: ^0.19.0
  image_cropper: ^5.0.0
#  flutter_image_compress: ^2.0.3
  pdf: ^3.10.3
  open_filex: ^4.3.2
  material_design_icons_flutter: ^7.0.7296
  # custom_searchable_dropdown: ^2.1.1
  device_imei: ^0.0.4+2
  animated_custom_dropdown: ^3.0.0
  url_launcher: ^6.1.11
  change_app_package_name: ^1.1.0
  freestyle_speed_dial: ^1.0.1+2
  collection: ^1.18.0
  grouped_list: ^5.1.2
  multi_select_flutter: ^4.1.3
  local_auth: ^2.2.0
  flutter_switch: ^0.3.2
  flutter_spinkit: ^5.2.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    